version: '3.8'
services:
  mariadb:
    image: 'mariadb:latest'
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - 'dbdata:/var/lib/mysql'
    networks:
      - phpnetwork

  laravel:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    ports:
      - '9000:9000'
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./app:/var/www/html
    networks:
      - phpnetwork
    depends_on:
      - mariadb

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - '${NGINX_PORT:-80}:80'
    volumes:
      - ./app:/var/www/html:delegated
      - nginxlogs:/var/log/nginx
    networks:
      - phpnetwork
    depends_on:
      - mariadb
      - laravel

networks:
  phpnetwork:
    driver: bridge

volumes:
  dbdata:
    driver: local
  nginxlogs:
    driver: local